modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/shedaniel/rare-ice/issues/"
logoFile="icon.png"
authors="shedaniel"
[[mods]]
    modId="rare-ice"
    version="${version}"
    displayName="Rare Ice"
    description='''
Adds rare ice into the world. Can you find them?
'''